/*
 * SEQUENCE 객체
 * 	- 번호 발생기 객체
 * 	- 정수값을 순차적으로 생성하는 객체
 * 	- PRIMARY KEY로 사용하는 번호(ID) 등에 사용하여 정수값을 생성하기 위한 용도로 많이 사용
*/
DROP SEQUENCE SEQ1;

CREATE SEQUENCE SEQ1
	START WITH 10
	INCREMENT BY 10
	MAXVALUE 200
	MINVALUE -200
	CYCLE
	CACHE 10;

ALTER SEQUENCE SEQ1
	INCREMENT BY 5
	MAXVALUE 250
	MINVALUE -100
	NOCYCLE
	NOCACHE;

DROP SEQUENCE SEQ1;

SELECT SEQ1.NEXTVAL FROM DUAL;
SELECT SEQ1.CURRVAL FROM DUAL;


CREATE SEQUENCE SEQ_TEMP;
CREATE TABLE TEMP(
	ID NUMBER PRIMARY KEY
);
INSERT INTO TEMP VALUES(SEQ_TEMP.NEXTVAL);
SELECT * FROM TEMP;


/*
 * NEXTVAL, CURRVAL을 사용할 수 있는 명령어
*  1. SELECT문 (서브쿼리X)
*  2. INSERT문의 VALUES절
*  3. INSERT문의 SELECT절
*  4. UPDAT문의 SELECT절
*
*  NEXTVAL, CURRVAL을 사용할 수 없는 명령어
*  1. VIEW를 사용하는 SELECT
*  2. DISTINCT 키워드가 있는 SELECT
*  3. GROUP BY, HAVING, ORDER BY가 있는 SELECT
*  4. SELECT, DELETE, UPDATE의 서브쿼리
*  5. CREATE TABLE, ALTER TABLE에서 사용하는 DEFAULT값
*/